services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TROVE_AUTH: ${DEMO_TROVE_AUTH}
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
    command: npm run dev
    environment:
      - PHASE_ENVIRONMENT=development
      - PHASE_SERVICE_TOKEN=${PHASE_SERVICE_TOKEN_DEV}
      # Optionally: Direct env vars
      # - DEMO_API_KEY=local-value1
      # - DEMO_DATABASE_URL=local-value2
      # - DEMO_ENCRYPTION_KEY=local-value3
      # - DEMO_SERVICE_URL=local-value4
      # - DEMO_SECRET_TOKEN=local-value5
    stop_grace_period: 1s
  app-staging:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TROVE_AUTH: ${DEMO_TROVE_AUTH}
    ports:
      - "3001:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
    command: npm run dev
    environment:
      - PHASE_ENVIRONMENT=staging
      - PHASE_SERVICE_TOKEN=${PHASE_SERVICE_TOKEN_STAGING}
      # Optionally: Direct env vars
      # - DEMO_API_KEY=local-value1
      # - DEMO_DATABASE_URL=local-value2
      # - DEMO_ENCRYPTION_KEY=local-value3
      # - DEMO_SERVICE_URL=local-value4
      # - DEMO_SECRET_TOKEN=local-value5
    stop_grace_period: 1s
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TROVE_AUTH: ${DEMO_TROVE_AUTH}
    ports:
      - "3002:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
    command: npm run dev
    environment:
      - PHASE_ENVIRONMENT=production
      - PHASE_SERVICE_TOKEN=${PHASE_SERVICE_TOKEN_PROD}
      # Optionally: Direct env vars
      # - DEMO_API_KEY=local-value1
      # - DEMO_DATABASE_URL=local-value2
      # - DEMO_ENCRYPTION_KEY=local-value3
      # - DEMO_SERVICE_URL=local-value4
      # - DEMO_SECRET_TOKEN=local-value5
    stop_grace_period: 1s
