name: Phase Demo CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: phase-demo:test
          push: false

      - name: Run container and test secrets
        env:
          PHASE_APP: example-app
          PHASE_ENVIRONMENT: staging
          PHASE_SERVICE_TOKEN: ${{ secrets.PHASE_SERVICE_TOKEN_STAGING }}
        run: |
          docker run -d \
            --name phase-demo \
            -p 3000:3000 \
            -e PHASE_APP \
            -e PHASE_ENVIRONMENT \
            -e PHASE_SERVICE_TOKEN \
            phase-demo:test

          # Wait for container to start
          sleep 5

          # Test the endpoint and capture response
          curl -s http://localhost:3000/env | tee response.json

          # Check that environment variables were actually set
          if grep -q '"DEMO_API_KEY":"Not set"' response.json; then
            echo "Error: DEMO_API_KEY was not set by Phase"
            exit 1
          fi

          if grep -q '"DEMO_DATABASE_URL":"Not set"' response.json; then
            echo "Error: DEMO_DATABASE_URL was not set by Phase"
            exit 1
          fi

          # Print the response for debugging
          echo "Environment variables successfully loaded from Phase:"
          cat response.json
