name: Phase Demo CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  demo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Phase secrets into environment
        uses: ./.github/actions/phase-secrets
        with:
          phase_token: ${{ secrets.PHASE_SERVICE_TOKEN_STAGING }}
          app: example-app
          environment: staging

      - name: Build container
        run: |
          docker build --build-arg TROVE_AUTH=${DEMO_TROVE_AUTH} -t demo-app .
